export default {
  adminTitle: 'Hash',
  day: '日',
  month: '月',
  year: '年',
  week: '周',
  search: '检索',
  sort: '排序',
  status: '状态',
  operating: '操作',
  check: '查看',
  export: '导出',
  add: '新增',
  create: '创建',
  finish: '完成',
  edit: '编辑',
  del: '删除',
  review: '审核',
  setTop: '置顶',
  cancelSetTop: '取消置顶',
  selectAll: '全选',
  read: '已读',
  unRead: '未读',
  doUpload: '点击上传',
  loading: '加载中...',
  updating: '收取中...',
  previous: '上一条',
  close: '关闭',
  next: '下一条',
  route: {
    dashboard: '首页',
    discount: '优惠',
    rebate: '返水',
    promote: '推广',
    mine: '我的',
    customerInfo: '客服',
    betMap: '投注记录',
    record: '记录',
    editPassword: '修改密码',
    mining: '挖矿收益',
    withdrawal: '提现',
    recharge: '充值',
    gameInfo: '游戏详情',
    withdrawalRecord: '提现记录',
    pointsDetails: '积分明细',
    pointShop: '积分商城'
  },
  login: {
    welcome: 'welcome',
    pleaseEnterUsername: '请输入您的用户名',
    pleaseEnterPwd: '请输入您的密码',
    pleaseConfirmPwd: '再确认您的密码',
    pleaseEnterTrcAddress: '请输入TRC20地址',
    pwdNotMatch: '两次输入的密码不一致',
    login: '登录',
    reg: '注册',
    buySomeFirst: '先去逛逛',
    contactUs: '联系我们',
    hasAccount: '已有账号？',
    loginNow: '立即登录',
    noAccount: '没有账号？',
    regNow: '立即注册',
    isRememberMe: '记住我',
    inviteCode: '邀请码',
    pleaseEnterInviteCode: '请输入邀请码',
    attachCode: '图片验证码',
    pleaseEnterAttachCode: '请输入图片验证码',
    registering: '注册中...',
    registerSuccess: '注册成功',
    loging: '登录中...'
  },
  home: {
    currencyPlatform: '数字货币抽奖平台',
    fair: '公平、安全、公开',
    hotActivity: '热门活动',
    blockchainGame: '区块链游戏',
    regBag: '注册钱包',
    regBagTitle: '数字币 【去中心化】钱包下载地址',
    tradeCurrency: '交易虚拟币',
    tradeCurrencyTitle: '数字货币交易所中购买TRX',
    transferLottery: '转账抽奖',
    transferLotteryTitle: '向本平台转账参与抽奖',
    transferTip: '向下方地址按规定金额转账后即成功参与抽奖',
    winMoney: '中奖回款',
    winMoneyTitle: '中奖自动回款',
    winMoneyTips: '中奖后系统10秒内自动反奖',
    viewTutorial: '查看教程',
    asSeenIn: 'AS SEEN IN',
    contactService: '联系专属客服',
    gameNow: '立即游戏',
    gameRule: '游戏规则',
    winRule: '中奖规则',
    winExp: '中奖实例',
    betAddress: '官方投注地址',
    telegram: 'telegram',
    whatsapp: 'WhatsApp',
    copy: '一键复制',
    process: '参与流程',
    problem: '常见问题',
    partner: '合作伙伴',
    contact: '联系我们',
    aboutUs: '关于我们',
    exchange: '货币兑换',
    doExchange: '兑换USDT/TRX',
    winRank: '全球排名',
    inviteTitle_1: '2022风口项目',
    inviteTitle_2: '在家躺赚USDT',
    saving: '保存中...',
    odds: '倍',
    platform: '平台',
    url: '网址',
    tutorial: '教程',
    regPopTitle: '新用户注册三重好礼',
    regPopContent_1: '立即开通0.5%流水返利',
    regPopContent_2: '立即开通最高1%的代理佣金返利',
    regPopContent_3: '实时查看投注返奖记录',
    scanToPay: '扫描下方二维码投注',
    exchanges: '兑换',
    budget: '预算',
    exchangeAddress: '钱包地址'
  },
  customer: {
    customer24: '客服24小时',
    doService: '为您竭诚服务',
    hasProblem: '如遇到问题需要需要帮助，请联系线上客服',
    ask: '咨询'
  },
  rank: {
    realTime: '实时派彩',
    dayRank: '日排行',
    weekRank: '周排行',
    monthRank: '月排行',
    address: '地址',
    moneyType: '币种',
    total: '总派彩',
    time: '时间'
  },
  discount: {
    discountTime: '活动时间',
    discountInfo: '活动详情'
  },
  promote: {
    bannerTitle1: '推者有礼',
    bannerTitle2: '人脉变钱买',
    bannerTitle3: '-呼朋呼友，享多多好礼-',
    firstUserNumber: '一级用户数',
    secondUserNumber: '二级用户数',
    thirdUserNumber: '三级用户数',
    first: '一级',
    second: '二级',
    third: '三级',
    commission: '佣金',
    betAmount: '投注',
    recommendRegisterFirst: '一级注册返佣',
    recommendRegisterSecond: '二级注册返佣',
    recommendRegisterThird: '三级注册返佣',
    recommendRechargeFirst: '一级充值返佣',
    recommendRechargeSecond: '二级充值返佣',
    recommendRechargeThird: '三级充值返佣',
    percent: '比例',
    shareTitle: '分享好友',
    saveQR: '保存二维码',
    copyTitle: '复制链接分享好友',
    copyLink: '复制链接',
    minWalletAmount: '最低结算金额：',
    ruleTitle: '活动规则',
    rule_1: '佣金结算发放时间:每日的00: 00: 00系统自动派发(发放前一日)',
    rule_2: '佣金计算方式',
    rule_3: '一级返佣=一级用户的总投注*',
    rule_4: '二级返佣=二级用户的总投注*',
    rule_5: '三级返佣=三级级用户的总投注*',
    shareQr: '二维码分享'
  },
  rebate: {
    rewardHis: '历史总返水',
    tranHis: '历史总投注',
    withdrawalSuccess: '已结算',
    amountNoWithdrawal: '未领取',
    rule_1: '返水结算发放时间:每日的00: 00:00系统自动派发(发放前一日)',
    rule_2: '返水计算方式-返水=用户的总投注*0.5%'
  },
  mine: {
    usdt: 'USDT',
    trx: 'TRX',
    accountChange: '账变记录',
    commissionRecord: '返水记录',
    rebateRecord: '返佣记录',
    profitAndLoss: '盈亏报表',
    auto: '自动',
    manual: '手动',
    integral: '积分',

    account: '账号',
    level: '等级',
    vip: 'VIP',
    trcAddress: 'TRC地址',
    bettingRecord: '投注记录',
    share: '分享好友',
    logout: '退出登录',

    // 挖矿收益
    settlement: '24小时收益',
    income: '收益',

    // 积分明细
    doIntegral: '影响积分',
    beforeIntegral: '操作前',
    afterIntegral: '操作后',

    // 提现
    balance: '余额',
    withdrawalTime: '24小时提现',
    withdrawalLimit: '每日提款限额: ',
    fee: '手续费:',
    toAccount: '至账户',
    addressPlaceholder: '地址(T开头)',
    pleaseEnterYourAddress: '填写您的提现地址',
    errorAddressLenth: '请输入正确的提现地址，地址长度为34个字符',
    withdrawing: '提现中...',
    withdrawalSuccess: '提现成功',
    pleaseEnterWithdrawalAmount: '请输入提现金额',
    pleaseEnterSecurityPwd: '输入您的交易密码',

    // 提现记录
    examineStatus: '状态',
    pending: '待审核',
    pass: '审核通过',
    fail: '不通过',
    under: '审核中',
    withdrawalInfo: '提现详情',
    withdrawAmount: '提现金额',
    withdrawHash: '交易Hash',
    withdrawAddress: '提现地址',
    auditTime: '审核时间',
    approvalTime: '通过时间',
    failReason: '失败原因',

    // 盈亏报表
    trxAmount: 'TRX充值金额',
    usdtAmount: 'USDT充值金额',

    // 投注记录
    betInfo: '投注详情',
    win: '中奖',
    tie: '和',
    lose: '未中奖',
    invalid: '无效',
    noDrawn: '未开奖',
    orderNo: '订单号',
    gameName: '游戏名称',
    rechargeToken: '充值币种',
    rechargeAmount: '充值金额',
    rechargeFirst: '是否首充',
    betAmount: '投注金额',
    winType: '状态',
    winAmount: '中奖金额',
    returnAmount: '退款金额',
    settlementMode: '结算方式',
    experience: '是否试玩',
    prizeDetail: '中奖详情',

    // 修改密码
    loginPassword: '修改密码',
    payPassword: '支付密码',
    oldPassword: '旧密码',
    newPassword: '新密码',
    confirmPassword: '再次确认',
    pleaseEnterOldPassword: '请输入旧密码',
    pleaseEnterNewPassword: '请输入新密码',
    pleaseEnterConfirmPassword: '请再次确认新密码',
    newPassCannotSameOld: '新密码不能与旧密码一致',
    passNotMatch: '两次输入的密码不一致',

    token: '币种类型',
    recordAmount: '影响金额',
    recordType: '类型',
    recordTime: '订单时间',

    withdraw: '提现',
    investment: '投注',
    winnng: '中奖',
    rebate: '返水',
    commission: '返佣',
    withdrawalFailRefund: '提现失败',
    profit: '余额宝收益',
    manualIn: '人工入款',
    manualOut: '人工出款',
    regGift: '注册赠送',
    building: '建设中...',

    sureLogout: '确定退出登录？'
  },

  lang: {
    switch: '语言切换成功，页面即将刷新！'
  },

  publicLang: {
    sortNotNone: '排序不能为空！',
    sortMustBeNum: '排序必须是正整数',
    tips: '提示',
    sure: '确认',
    normal: '启用',
    disable: '禁用',
    recommend: '推荐',
    cancel_recommend: '取消推荐',
    confirmButton: '确定',
    cancelButton: '取消',
    closeButton: '关闭',
    saveButton: '保存',
    createSuccess: '创建成功',
    updateSuccess: '修改成功',
    deleteSuccess: '删除成功',
    resetSuccess: '重置成功',
    setSuccess: '设置成功',
    setFailed: '设置失败',
    remark: '备注',
    reset: '重置',
    clear: '清空',
    yuan: '元',
    notNull: '不能为空',
    must100: '必须是100以内的正整数,可以是0!',
    mustInt: '必须是正整数!',
    mustIntAndFloat: '必须是正整数,允许包含2位小数,可以是0!',
    googleCode: '谷歌验证码',
    pleaseEnterGoogleCode: '请输入6位数谷歌验证码',
    wrongCode: '验证码错误',
    startTime: '开始时间',
    entTime: '结束时间',
    today: '今天',
    yesterday: '昨天',
    nearlySevenDays: '近7天',
    thisMonth: '本月',
    lastMonth: '上月',
    tomorrow: '明天',
    afterAweek: '一周后',
    copy: '复制',
    copySuccess: '复制成功',
    copyError: '复制失败',
    yes: '是',
    no: '否',
    seconds: '秒',
    noData: '暂无数据',
    headerNoSign: '返回头中未获取到签名！',
    noSign: '验签失败，请联系管理员！',
    day: '天'
  },

  // ========== 组件
  components: {
    downApp: '下载APP',
    down: '下载中...',
    clickDown: '点击下载'
  },

  // ========== 系统提示
  msg: {
    loginExpired: '登录过期，请重新登录！',
    accountNoRoles: '当前登录用户未分配权限，请联系管理员！',
    connectErr: '连接异常',
    goChangePwd: '当前用户密码已经超过三个月未修改，请修改登录密码！',
    dataError: '数据错误，请稍后重试！',
    connectError: '服务器连接失败，请稍后重试'
  }
}
